# Generated by Django 4.0.1 on 2022-02-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('statue', models.CharField(choices=[('A', 'Available'), ('O', 'outStock')], max_length=10)),
                ('count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('suppler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplers')),
            ],
        ),
    ]
