# Generated by Django 4.0.1 on 2022-01-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('statius', models.CharField(choices=[('A', 'Aviable'), ('O', 'OutStock')], max_length=1)),
                ('count', models.IntegerField()),
                ('image', models.ImageField(upload_to='img/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('suppler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplers')),
            ],
        ),
    ]
