# Generated by Django 4.0.1 on 2022-02-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_stocks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='status',
            field=models.CharField(choices=[('Aviable', 'A'), ('OutStock', 'O')], max_length=10),
        ),
    ]
