# Generated by Django 4.0.1 on 2022-02-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_stocks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='image',
            field=models.ImageField(upload_to='base/img/products'),
        ),
    ]
