# Generated by Django 4.0.1 on 2022-01-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_stocks_p_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='P_Date',
        ),
    ]
