# Generated by Django 4.0.1 on 2022-01-29 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_stocks_p_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='P_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
