# Generated by Django 4.0.1 on 2022-01-29 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppler',
            fields=[
                ('S_id', models.IntegerField(primary_key=True, serialize=False)),
                ('S_name', models.CharField(max_length=100)),
                ('S_descrition', models.TextField(blank=True, null=True)),
                ('S_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_name', models.CharField(max_length=100)),
                ('P_count', models.IntegerField()),
                ('P_status', models.CharField(choices=[('A', 'Available'), ('O', 'Out')], max_length=1)),
                ('P_Date', models.DateTimeField(default=datetime.datetime.now)),
                ('P_description', models.TextField(blank=True, null=True)),
                ('S_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.suppler')),
            ],
        ),
    ]
